version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "06:00"
      timezone: "UTC"
    open-pull-requests-limit: 20
    labels:
      - "dependencies"
    commit-message:
      prefix: "chore(deps)"
    versioning-strategy: increase-if-necessary

  - package-ecosystem: "npm"
    directory: "/private/rutinas"
    schedule:
      interval: "daily"
      time: "06:10"
      timezone: "UTC"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
    commit-message:
      prefix: "chore(deps)"
    versioning-strategy: increase-if-necessary

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:20"
      timezone: "UTC"
    labels:
      - "dependencies"
    commit-message:
      prefix: "chore(ci)"

  - package-ecosystem: "terraform"
    directory: "/infra/github/src"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:30"
      timezone: "UTC"
    labels:
      - "dependencies"
    commit-message:
      prefix: "chore(tf)"

  - package-ecosystem: "terraform"
    directory: "/infra/vercel/web/src"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:40"
      timezone: "UTC"
    labels:
      - "dependencies"
    commit-message:
      prefix: "chore(tf)"
