/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LangRouteImport } from './routes/$lang'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LangIndexRouteImport } from './routes/$lang/index'
import { Route as LangSearchRouteImport } from './routes/$lang/search'
import { Route as LangTopicsIndexRouteImport } from './routes/$lang/topics/index'
import { Route as LangTopicsTopicRouteImport } from './routes/$lang/topics/$topic'
import { Route as LangBlogSlugRouteImport } from './routes/$lang/blog/$slug'

const LangRoute = LangRouteImport.update({
  id: '/$lang',
  path: '/$lang',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LangIndexRoute = LangIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LangRoute,
} as any)
const LangSearchRoute = LangSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => LangRoute,
} as any)
const LangTopicsIndexRoute = LangTopicsIndexRouteImport.update({
  id: '/topics/',
  path: '/topics/',
  getParentRoute: () => LangRoute,
} as any)
const LangTopicsTopicRoute = LangTopicsTopicRouteImport.update({
  id: '/topics/$topic',
  path: '/topics/$topic',
  getParentRoute: () => LangRoute,
} as any)
const LangBlogSlugRoute = LangBlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => LangRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteWithChildren
  '/$lang/search': typeof LangSearchRoute
  '/$lang/': typeof LangIndexRoute
  '/$lang/blog/$slug': typeof LangBlogSlugRoute
  '/$lang/topics/$topic': typeof LangTopicsTopicRoute
  '/$lang/topics/': typeof LangTopicsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$lang/search': typeof LangSearchRoute
  '/$lang': typeof LangIndexRoute
  '/$lang/blog/$slug': typeof LangBlogSlugRoute
  '/$lang/topics/$topic': typeof LangTopicsTopicRoute
  '/$lang/topics': typeof LangTopicsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteWithChildren
  '/$lang/search': typeof LangSearchRoute
  '/$lang/': typeof LangIndexRoute
  '/$lang/blog/$slug': typeof LangBlogSlugRoute
  '/$lang/topics/$topic': typeof LangTopicsTopicRoute
  '/$lang/topics/': typeof LangTopicsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$lang'
    | '/$lang/search'
    | '/$lang/'
    | '/$lang/blog/$slug'
    | '/$lang/topics/$topic'
    | '/$lang/topics/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$lang/search'
    | '/$lang'
    | '/$lang/blog/$slug'
    | '/$lang/topics/$topic'
    | '/$lang/topics'
  id:
    | '__root__'
    | '/'
    | '/$lang'
    | '/$lang/search'
    | '/$lang/'
    | '/$lang/blog/$slug'
    | '/$lang/topics/$topic'
    | '/$lang/topics/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LangRoute: typeof LangRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$lang': {
      id: '/$lang'
      path: '/$lang'
      fullPath: '/$lang'
      preLoaderRoute: typeof LangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/': {
      id: '/$lang/'
      path: '/'
      fullPath: '/$lang/'
      preLoaderRoute: typeof LangIndexRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/search': {
      id: '/$lang/search'
      path: '/search'
      fullPath: '/$lang/search'
      preLoaderRoute: typeof LangSearchRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/topics/': {
      id: '/$lang/topics/'
      path: '/topics'
      fullPath: '/$lang/topics/'
      preLoaderRoute: typeof LangTopicsIndexRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/topics/$topic': {
      id: '/$lang/topics/$topic'
      path: '/topics/$topic'
      fullPath: '/$lang/topics/$topic'
      preLoaderRoute: typeof LangTopicsTopicRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/blog/$slug': {
      id: '/$lang/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/$lang/blog/$slug'
      preLoaderRoute: typeof LangBlogSlugRouteImport
      parentRoute: typeof LangRoute
    }
  }
}

interface LangRouteChildren {
  LangSearchRoute: typeof LangSearchRoute
  LangIndexRoute: typeof LangIndexRoute
  LangBlogSlugRoute: typeof LangBlogSlugRoute
  LangTopicsTopicRoute: typeof LangTopicsTopicRoute
  LangTopicsIndexRoute: typeof LangTopicsIndexRoute
}

const LangRouteChildren: LangRouteChildren = {
  LangSearchRoute: LangSearchRoute,
  LangIndexRoute: LangIndexRoute,
  LangBlogSlugRoute: LangBlogSlugRoute,
  LangTopicsTopicRoute: LangTopicsTopicRoute,
  LangTopicsIndexRoute: LangTopicsIndexRoute,
}

const LangRouteWithChildren = LangRoute._addFileChildren(LangRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LangRoute: LangRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
