/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TopicsIndexRouteImport } from './routes/topics/index'
import { Route as EsIndexRouteImport } from './routes/es/index'
import { Route as TopicsTopicRouteImport } from './routes/topics/$topic'
import { Route as EsSearchRouteImport } from './routes/es/search'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as EsTopicsIndexRouteImport } from './routes/es/topics/index'
import { Route as EsTopicsTopicRouteImport } from './routes/es/topics/$topic'
import { Route as EsBlogSlugRouteImport } from './routes/es/blog/$slug'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TopicsIndexRoute = TopicsIndexRouteImport.update({
  id: '/topics/',
  path: '/topics/',
  getParentRoute: () => rootRouteImport,
} as any)
const EsIndexRoute = EsIndexRouteImport.update({
  id: '/es/',
  path: '/es/',
  getParentRoute: () => rootRouteImport,
} as any)
const TopicsTopicRoute = TopicsTopicRouteImport.update({
  id: '/topics/$topic',
  path: '/topics/$topic',
  getParentRoute: () => rootRouteImport,
} as any)
const EsSearchRoute = EsSearchRouteImport.update({
  id: '/es/search',
  path: '/es/search',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EsTopicsIndexRoute = EsTopicsIndexRouteImport.update({
  id: '/es/topics/',
  path: '/es/topics/',
  getParentRoute: () => rootRouteImport,
} as any)
const EsTopicsTopicRoute = EsTopicsTopicRouteImport.update({
  id: '/es/topics/$topic',
  path: '/es/topics/$topic',
  getParentRoute: () => rootRouteImport,
} as any)
const EsBlogSlugRoute = EsBlogSlugRouteImport.update({
  id: '/es/blog/$slug',
  path: '/es/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/search': typeof SearchRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/es/search': typeof EsSearchRoute
  '/topics/$topic': typeof TopicsTopicRoute
  '/es/': typeof EsIndexRoute
  '/topics/': typeof TopicsIndexRoute
  '/es/blog/$slug': typeof EsBlogSlugRoute
  '/es/topics/$topic': typeof EsTopicsTopicRoute
  '/es/topics/': typeof EsTopicsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/search': typeof SearchRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/es/search': typeof EsSearchRoute
  '/topics/$topic': typeof TopicsTopicRoute
  '/es': typeof EsIndexRoute
  '/topics': typeof TopicsIndexRoute
  '/es/blog/$slug': typeof EsBlogSlugRoute
  '/es/topics/$topic': typeof EsTopicsTopicRoute
  '/es/topics': typeof EsTopicsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/search': typeof SearchRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/es/search': typeof EsSearchRoute
  '/topics/$topic': typeof TopicsTopicRoute
  '/es/': typeof EsIndexRoute
  '/topics/': typeof TopicsIndexRoute
  '/es/blog/$slug': typeof EsBlogSlugRoute
  '/es/topics/$topic': typeof EsTopicsTopicRoute
  '/es/topics/': typeof EsTopicsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/search'
    | '/blog/$slug'
    | '/es/search'
    | '/topics/$topic'
    | '/es/'
    | '/topics/'
    | '/es/blog/$slug'
    | '/es/topics/$topic'
    | '/es/topics/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/search'
    | '/blog/$slug'
    | '/es/search'
    | '/topics/$topic'
    | '/es'
    | '/topics'
    | '/es/blog/$slug'
    | '/es/topics/$topic'
    | '/es/topics'
  id:
    | '__root__'
    | '/'
    | '/search'
    | '/blog/$slug'
    | '/es/search'
    | '/topics/$topic'
    | '/es/'
    | '/topics/'
    | '/es/blog/$slug'
    | '/es/topics/$topic'
    | '/es/topics/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SearchRoute: typeof SearchRoute
  BlogSlugRoute: typeof BlogSlugRoute
  EsSearchRoute: typeof EsSearchRoute
  TopicsTopicRoute: typeof TopicsTopicRoute
  EsIndexRoute: typeof EsIndexRoute
  TopicsIndexRoute: typeof TopicsIndexRoute
  EsBlogSlugRoute: typeof EsBlogSlugRoute
  EsTopicsTopicRoute: typeof EsTopicsTopicRoute
  EsTopicsIndexRoute: typeof EsTopicsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topics/': {
      id: '/topics/'
      path: '/topics'
      fullPath: '/topics/'
      preLoaderRoute: typeof TopicsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/es/': {
      id: '/es/'
      path: '/es'
      fullPath: '/es/'
      preLoaderRoute: typeof EsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topics/$topic': {
      id: '/topics/$topic'
      path: '/topics/$topic'
      fullPath: '/topics/$topic'
      preLoaderRoute: typeof TopicsTopicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/es/search': {
      id: '/es/search'
      path: '/es/search'
      fullPath: '/es/search'
      preLoaderRoute: typeof EsSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/es/topics/': {
      id: '/es/topics/'
      path: '/es/topics'
      fullPath: '/es/topics/'
      preLoaderRoute: typeof EsTopicsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/es/topics/$topic': {
      id: '/es/topics/$topic'
      path: '/es/topics/$topic'
      fullPath: '/es/topics/$topic'
      preLoaderRoute: typeof EsTopicsTopicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/es/blog/$slug': {
      id: '/es/blog/$slug'
      path: '/es/blog/$slug'
      fullPath: '/es/blog/$slug'
      preLoaderRoute: typeof EsBlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SearchRoute: SearchRoute,
  BlogSlugRoute: BlogSlugRoute,
  EsSearchRoute: EsSearchRoute,
  TopicsTopicRoute: TopicsTopicRoute,
  EsIndexRoute: EsIndexRoute,
  TopicsIndexRoute: TopicsIndexRoute,
  EsBlogSlugRoute: EsBlogSlugRoute,
  EsTopicsTopicRoute: EsTopicsTopicRoute,
  EsTopicsIndexRoute: EsTopicsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
